version: '3.3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - /home/username/.authelia/Configs:/config #change this to a shared folder on your system. DO NOT use a "volume"
    ports:
      - 9091:9091
    environment:
      - TZ=America/New York
    env_file:
      - .env
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - /home/username/.authelia/Configs/mysql/data:/var/lib/mysql
      - /home/username/.authelia/Configs/mysql/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
