version: '3'

services:
  camera1:
    image: kerberos/kerberos
    container_name: kerberos-testenv
    ports:
      - "80:80"
      - "8889:8889"
    volumes:
      - ./config:/etc/opt/kerberosio/config
      - ./capture:/etc/opt/kerberosio/capture
      - ./logs:/etc/opt/kerberosio/logs
      - ./webconfig:/var/www/web/config
    restart: always
